In [9]:
import numpy as np

M = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0]])

D = np.array([3,3,3])

R = (1/np.sqrt(D)) * M * (1/np.sqrt(D))

print (M)
print (R)

[[0 0 0]
 [1 0 0]
 [0 1 0]]
[[0.         0.         0.        ]
 [0.33333333 0.         0.        ]
 [0.         0.33333333 0.        ]]
